#!/usr/bin/env bash

readonly BACKUP_DIR=~/dotfiles/home_backup/
readonly IGNORE=(.git .gitignore .swp$)
readonly SCRIPT_DIR=$(dirname "$0")

in_ignore () {
    for i in "${IGNORE[@]}"; do
	if [[ "$1" =~ $i ]]; then
            return 0
	fi
    done
    return 1
}

remove_existing_dir () {
    local basename
    basename=$(basename "$1")
    local target_dir=~/$basename
    if [[ -d $1 && -d $target_dir ]]; then
	echo "target $target_dir"
	rm -rf "$target_dir"
    fi
}
        
echo 'Backing up Home Directory dotfiles...'

if [[ ! -d $BACKUP_DIR ]]; then
    mkdir -v $BACKUP_DIR
fi

rsync -r --no-links ~/.[^.]* $BACKUP_DIR
if [[ "$?" -ne 0 ]]; then
    exit 1
fi

echo 'Creating links to dotfiles...'

cd "$(pwd)/$SCRIPT_DIR" || exit 1

for f in ./.[^.]*; do
    basename=$(basename "$f")
    in_ignore "$(basename "$f")"
    if [[ "$?" -ne 0 ]]; then
	remove_existing_dir "$f"
	ln -svf "$(pwd)/$basename" ~/
    fi
done

