#!/usr/bin/env bash

readonly BACKUP_DIR=~/dotfiles/home_backup/dotfiles/
readonly IGNORE=(.git .gitignore .swp$)
readonly SCRIPT_DIR=$(dirname "$0")

# Check if a fil is in the IGNORE list
in_ignore () {
    for i in "${IGNORE[@]}"; do
	if [[ "$1" =~ $i ]]; then
            return 0
	fi
    done
    return 1
}

# Remove existing directory to make way for the link
remove_existing_dir () {
    local basename
    basename=$(basename "$1")
    local target_dir=~/$basename
    if [[ -d $1 && -d $target_dir ]]; then
	echo "target $target_dir"
	rm -rf "$target_dir"
    fi
}
        
cd "$(pwd)/$SCRIPT_DIR" || exit 1

echo 'Backing up and creating links to dotfiles...'

# Create the backup directory if it doesn't exist
if [[ ! -d "$BACKUP_DIR" ]]; then
    mkdir -v "$BACKUP_DIR"
fi

# Backup dotfiles in the HOME directory and link dotfiles into it
for f in ./.[^.]*; do
    basename=$(basename "$f")
    # Check if the file is in the IGNORE list
    in_ignore "$(basename "$f")"
    if [[ "$?" -ne 0 ]]; then
	# Backup file
        rsync -rv --no-links "$HOME/$basename" "$BACKUP_DIR"
	remove_existing_dir "$f"
	# Link to dotfile
	ln -svf "$(pwd)/$basename" ~/
    fi
done

if [[ "$?" == 0 ]]; then
    echo Done
fi

