#!/usr/bin/env bash

readonly BACKUP_DIR=~/dotfiles/home_backup/
readonly SCRIPT_DIR=`dirname "$0"`

if [[ ! -d $BACKUP_DIR ]]; then
    echo 'No backup found' >/dev/stderr
    exit 1
fi

cd $(pwd)/$SCRIPT_DIR

echo 'Removing links...'

find ~/ -lname "$(pwd)/.*" -delete 

echo 'Restoring from backup...'

cp -r $BACKUP_DIR.[^.]* ~/

