#!/usr/bin/env bash

readonly BACKUP_DIR=~/dotfiles/backup/vim
readonly SCRIPT_DIR=`dirname "$0"`

# Exit if there is no backup directory
if [[ ! -d $BACKUP_DIR ]]; then
    echo 'No backup found' >/dev/stderr
    exit 1
fi

cd "$(pwd)/$SCRIPT_DIR" || exit 1

# Restore ftplugin files
echo 'Removing links...'

find "$HOME/.vim/after/ftplugin" -lname "$(pwd)/vim/ftplugin/*" -print -delete 

echo 'Restoring from backup...'

cp -rv $BACKUP_DIR/ftplugin/*.vim $HOME/.vim/after/ftplugin/

if [[ "$?" == 0 ]]; then
    echo 'Vim restauration complete'
fi

