#!/usr/bin/env bash

readonly SCRIPT_DIR=$(dirname "$0")

cd "$(pwd)/$SCRIPT_DIR" || exit 1

source ./scripts/helpers.sh

# Option List
optlist=":aAdhTv"

# Process help first
while getopts $optlist options; do
    case ${options} in
	h)
	    cat ./text/restore-help.txt
	    exit 0
	    ;;
    esac
done
OPTIND=1

# Process the run All scripts option in priority
while getopts $optlist options; do
    case ${options} in
	A) 
	    msg_info 'Running All restore scripts'
	    ./scripts/restore-dotfiles
	    ./scripts/restore-terminal
	    ./scripts/restore-vim
            if [[ "$?" == 0 ]]; then
                msg_success 'Restoration script run successfullyr'
	        exit 0 
            fi
	    ;;
    esac
done
OPTIND=1

# Then process the run almost all scripts option
while getopts $optlist options; do
    case ${options} in
	a) 
	    msg_info 'Running Almost all restore scripts'
	    ./scripts/restore-dotfiles
	    ./scripts/restore-vim
            if [[ "$?" == 0 ]]; then
                msg_success 'Restoration script run successfully'
	        exit 0 
            fi
	    ;;
    esac
done
OPTIND=1

# Finally process the rest of the options
while getopts $optlist options; do
    case ${options} in
	d) msg_info 'Running restore-dotfiles...' 
	./scripts/restore-dotfiles
	;;
        T) msg_info 'Running restore-terminal...'
	./scripts/restore-terminal
	;;
	v) msg_info 'Running restore-vim...' 
	./scripts/restore-vim
	;;
	\?) echo "Invalid option: $OPTARG" 1>&2
            echo "Try './install -h' for more information" 1>&2
	    exit 1
	    ;;
    esac
done
shift $((OPTIND -1))

handle_missing_option OPTIND
handle_invalid_arg "$#" "$@"

if [[ "$?" == 0 ]]; then
    msg_success 'Restoration script run successfully'
fi

