#!/usr/bin/env bash

readonly BACKUP_DIR=~/dotfiles/home_backup/dotfiles/
readonly SCRIPT_DIR=`dirname "$0"`

# Create backup directory if it doesn't exist
if [[ ! -d $BACKUP_DIR ]]; then
    echo 'No backup found' >/dev/stderr
    exit 1
fi

cd $(pwd)/$SCRIPT_DIR

echo 'Removing links...'

find ~/ -lname "$(pwd)/.*" -print -delete 

echo 'Restoring from backup...'

cp -rv $BACKUP_DIR.[^.]* ~/

if [[ "$?" == 0 ]]; then
    echo Done
fi

