#!/usr/bin/env bash

readonly BACKUP_DIR=~/dotfiles/backup/dotfiles/
readonly SCRIPT_DIR=`dirname "$0"`

# Exit if there is no backup directory
if [[ ! -d $BACKUP_DIR ]]; then
    echo 'No backup found' >/dev/stderr
    exit 1
fi

cd $(pwd)/$SCRIPT_DIR

echo 'Removing links...'

find $HOME -lname "$(pwd)/dotfiles/.*" -print -delete 

echo 'Restoring from backup...'

cp -rv $BACKUP_DIR.[^.]* $HOME 

if [[ "$?" == 0 ]]; then
    echo Done
fi

