#!/usr/bin/env bash

readonly SCRIPT_DIR=$(dirname "$0")

cd "$(pwd)/$SCRIPT_DIR" || exit 1

source ./scripts/colors

# Option List
optlist=":aAdhTv"

# Process help first
while getopts $optlist options; do
    case ${options} in
	h)
	    cat ./text/restore-help.txt
	    exit 0
	    ;;
    esac
done
OPTIND=1

# Process the run All scripts option in priority
while getopts $optlist options; do
    case ${options} in
	A) 
	    echo -e "${BLUE}Running All restore scripts${RESET_FORMAT}"
	    ./scripts/restore-dotfiles
	    ./scripts/restore-terminal
	    ./scripts/restore-vim
            if [[ "$?" == 0 ]]; then
                echo -e "${GREEN}Restoration script run successfullyr${RESET_FORMAT}"
	        exit 0 
            fi
	    ;;
    esac
done
OPTIND=1

# Then process the run almost all scripts option
while getopts $optlist options; do
    case ${options} in
	a) 
	    echo -e "${BLUE}Running Almost all restore scripts${RESET_FORMAT}"
	    ./scripts/restore-dotfiles
	    ./scripts/restore-vim
            if [[ "$?" == 0 ]]; then
                echo -e "${GREEN}Restoration script run successfully${RESET_FORMAT}"
	        exit 0 
            fi
	    ;;
    esac
done
OPTIND=1

# Finally process the rest of the options
while getopts $optlist options; do
    case ${options} in
	d) echo -e "${BLUE}Running restore-dotfiles...${RESET_FORMAT}" 
	./scripts/restore-dotfiles
	;;
        T) echo -e "${BLUE}Running restore-terminal...${RESET_FORMAT}"
	./scripts/restore-terminal
	;;
	v) echo -e "${BLUE}Running restore-vim...${RESET_FORMAT}" 
	./scripts/restore-vim
	;;
	\?) echo "Invalid option: $OPTARG" 1>&2
            echo "Try './install -h' for more information" 1>&2
	    exit 1
	    ;;
    esac
done
shift $((OPTIND -1))

# Handle missing option
if ((OPTIND == 1)); then
    echo 'Missing option' 1>&2
    echo "Try './install -h' for more information" 1>&2
    exit 1
fi

# Handle invalid arguments
if [[ "$#" > 0 ]]; then
    echo "Unrecognized argument(s): $@" 1>&2
    echo "Try './install -h' for more information" 1>&2
    exit 1
fi

if [[ "$?" == 0 ]]; then
    echo -e "${GREEN}Restoration script run successfully${RESET_FORMAT}"
fi

