# Don't print a new line at the start of the prompt
add_newline = false

[character]
# Replace prompt symbol
symbol = "$"

[cmd_duration]
# Disable the time taken by last command
disabled = true

[directory]
# Number of parent folders shown
truncation_length = 8
# Still show the normal path when inside a git repo
truncate_to_repo = false
style = "bold blue"

[git_branch]
style = "#86c5da"

[git_status]
style = "bold yellow"

[line_break]
# Keep prompt on one line
disabled = true

