# Don't print a new line at the start of the prompt
add_newline = false

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[character]
# Replace prompt symbol
symbol = "$"

[cmd_duration]
# Disable the time taken by last command
disabled = true

[conda]
symbol = " "

[directory]
# Number of parent folders shown
truncation_length = 8
# Still show the normal path when inside a git repo
truncate_to_repo = false
style = "bold blue"

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
style = "bold cyan"
symbol = " "

[git_status]
style = "bold yellow"

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[line_break]
# Keep prompt on one line
disabled = true

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

