#!/usr/bin/env bash

readonly BASE_DIR=$(dirname "$0")/..

cd "$(pwd)/$BASE_DIR" || exit 1

source ./scripts/colors

echo -e "${BLUE}Installing command line tools... ${RESET_FORMAT}"

# Install Starship prompt
if ! starship -V ; then
    curl -fsSL https://starship.rs/install.sh | bash
fi
 
# Install tldr pages
if ! tldr -V ; then
    npm install -g tldr
fi

if [[ "$?" == 0 ]]; then
    echo -e "${GREEN}Command line tools installation complete ${RESET_FORMAT}"
fi

