#!/usr/bin/env bash

readonly BASE_DIR=$(dirname "$0")/..

cd "$(pwd)/$BASE_DIR" || exit 1

# shellcheck source=./helpers.sh
source ./scripts/helpers.sh

msg_info 'Installing command line tools...'

# Install Starship prompt
if ! starship -V ; then
    curl -fsSL https://starship.rs/install.sh | bash
fi
 
# Install tldr pages
if ! tldr -V ; then
    npm install -g tldr
fi

if [[ "$?" == 0 ]]; then
    msg_success 'Command line tools installation complete'
fi

