#!/usr/bin/env bash

readonly BASE_DIR=$(dirname "$0")/..

cd "$(pwd)/$BASE_DIR" || exit 1

# shellcheck source=./helpers.sh
source ./scripts/helpers.sh

msg_info 'Installing deb packages...'

# Update and upgrade package manager
sudo apt update
sudo apt upgrade

# Install cURL if necessary
if ! curl -V ; then
    sudo apt install curl
fi
# Install Python
if ! python3 -V ; then
    sudo apt install python3
fi

# Install pip
if ! python3 -m pip -V ; then
    sudo apt install python3-venv python3-pip
fi

npm install npm@latest -g

# Install nvm
if ! nvm -v ; then
    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Install and use latest LTS version of node.js using nvm
nvm install --lts
nvm use --lts

# Install yarn
if ! yarn --version ; then
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt update && sudo apt install --no-install-recommends yarn || sudo apt install yarn
fi

# Install Ruby
if ! ruby -v ; then
    sudo apt install ruby-full
fi

if ! vim --version ; then
    sudo apt install vim
fi

if [[ "$?" == 0 ]]; then
    msg_warning 'Please relaunch the terminal for the changes to take effect'
    msg_success 'Deb packages installation complete'
fi

