#!/usr/bin/env bash

readonly BACKUP_DIR=$HOME/dotfiles/backup/dotfiles/
readonly IGNORE=(.git .gitignore .swp$)
readonly BASE_DIR=$(dirname "$0")/..

cd "$(pwd)/$BASE_DIR" || exit 1

# shellcheck source=./helpers.sh
source ./scripts/helpers.sh

# Check if a fil is in the IGNORE list
in_ignore () {
    for i in "${IGNORE[@]}"; do
	if [[ "$1" =~ $i ]]; then
            return 0
	fi
    done
    return 1
}

msg_info 'Backing up and creating links to dotfiles...'

# Create the backup directory if it doesn't exist
mkdir -pv "$BACKUP_DIR"

vimrc=false

# Backup dotfiles in the HOME directory and link dotfiles into it
for f in ./dotfiles/.[^.]*; do
    basename=$(basename "$f")
    # Check if .vimrc is used
    if [[ $basename == '.vimrc' ]]; then
	vimrc=true
    fi
    # Check if the file is in the IGNORE list
    in_ignore "$(basename "$f")"
    if [[ "$?" -ne 0 ]]; then
	# Backup file
	if [[ -f "$HOME/$basename" ]]; then
	    backup_file "$HOME/$basename" "$BACKUP_DIR"
	fi
	remove_existing_dir "$f"
	# Link to dotfile
	make_link "$(pwd)/dotfiles/$basename" "$HOME"
    fi
done

# If .vimrc is used, launch Vim, install plugins and quit
if [[ $vimrc ]]; then
    msg_info 'Installing Vim plugins...'
    vim +'PlugInstall --sync' +qa
fi

if [[ "$?" == 0 ]]; then
    msg_success 'Dotfiles installation complete'
fi

