#!/usr/bin/env bash

readonly BACKUP_DIR=$HOME/dotfiles/backup/dotfiles/
readonly BASE_DIR=$(dirname "$0")/..

cd "$(pwd)/$BASE_DIR" || exit 1

# shellcheck source=./helpers.sh
source ./scripts/helpers.sh

msg_info 'Removing links...'

# Exit if there is no backup directory
if [[ ! -d $BACKUP_DIR ]]; then
    msg_alert 'No backup found' >/dev/stderr
    exit 1
fi

find "$HOME" -lname "$(pwd)/dotfiles/.*" -print -delete 

msg_info 'Restoring from backup...'

cp -frv "$BACKUP_DIR".[^.]* "$HOME" 

if [[ "$?" == 0 ]]; then
    msg_success 'Dotfiles restauration complete'
fi

