#!/usr/bin/env bash

readonly BACKUP_DIR=$HOME/dotfiles/backup/vim
readonly BASE_DIR=$(dirname "$0")/..

cd "$(pwd)/$BASE_DIR" || exit 1

# shellcheck source=./helpers.sh
source ./scripts/helpers.sh

# Exit if there is no backup directory
if [[ ! -d $BACKUP_DIR ]]; then
    msg_alert 'No backup found' >/dev/stderr
    exit 1
fi

# Restore ftplugin files
msg_info 'Removing links...'

find "$HOME/.vim/after/ftplugin" -lname "$(pwd)/vim/ftplugin/*" -print -delete 

msg_info 'Restoring from backup...'

cp -frv "$BACKUP_DIR"/ftplugin/*.vim "$HOME/.vim/after/ftplugin/"

if [[ "$?" == 0 ]]; then
    msg_success 'Vim restauration complete'
fi

