#!/usr/bin/env bash

readonly BACKUP_DIR=$HOME/dotfiles/backup/terminal
readonly BASE_DIR=$(dirname "$0")/..
readonly USER_STRING='ben*'

cd "$(pwd)/$BASE_DIR" || exit 1

# Import system functions
source ./scripts/system.sh

# Restore backup configuration file for WSL
if [[ $(get_os) = 'wsl' ]]; then
    user_path=$(find /mnt/c/Users/ -maxdepth 1 -type d -iname $USER_STRING)
    config_path=$user_path/AppData/Roaming/wsltty
    # Restore backup config file
    cp -fv "$BACKUP_DIR/wsltty/config" "$config_path/"
fi

# Restore configuration for Linux terminal
if [[ $(get_os) = 'linux' ]]; then
    # Restore default terminal configuration
    terminal_profile=$(gsettings get org.gnome.Terminal.ProfilesList default | awk -F \' '{print $2}')
    gsettings reset org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/ use-system-font
    gsettings reset org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/ font
fi

if [[ "$?" == 0 ]]; then
    echo 'Terminal configuration restoration complete'
fi

