#!/usr/bin/env bash

readonly BACKUP_DIR=$HOME/dotfiles/backup/vim
readonly BASE_DIR=$(dirname "$0")/..

cd "$(pwd)/$BASE_DIR" || exit 1

source ./scripts/colors

# Exit if there is no backup directory
if [[ ! -d $BACKUP_DIR ]]; then
    echo -e "${RED_BOLD}No backup found${RESET_FORMAT}" >/dev/stderr
    exit 1
fi

# Restore ftplugin files
echo -e "${BLUE}Removing links...${RESET_FORMAT}"

find "$HOME/.vim/after/ftplugin" -lname "$(pwd)/vim/ftplugin/*" -print -delete 

echo -e "${BLUE}Restoring from backup...${RESET_FORMAT}"

cp -frv $BACKUP_DIR/ftplugin/*.vim $HOME/.vim/after/ftplugin/

if [[ "$?" == 0 ]]; then
    echo -e "${GREEN}Vim restauration complete${RESET_FORMAT}"
fi

