#!/usr/bin/env bash

readonly BACKUP_DIR=$HOME/dotfiles/backup/terminal
readonly BASE_DIR=$(dirname "$0")/..
readonly USER_STRING='ben*'
readonly RED_BOLD='\033[1;91m'
readonly RESET_FORMAT='\033[0m'

cd "$(pwd)/$BASE_DIR" || exit 1

# Import system functions
source ./scripts/system.sh

# Create the backup directory if it doesn't exist
mkdir -pv "$BACKUP_DIR"

# Backup and link terminal configuration file for WSL
if [[ $(get_os) = 'wsl' ]]; then
    # Check if the font is installed
    is_font=$(find /mnt/c/Windows/Fonts/ -maxdepth 1 -type f -iname 'Droid*') 
    if [[ -z $is_font ]]; then
	cd ./font/
	url='https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.otf'	
        curl -fLo "Droid Sans Mono Nerd Font Complete Mono Windows Compatible.otf" $url 
	# Open the Windows explorer so the user can install the font
	explorer.exe .
	cd ..
	# Message to install font
	echo -e "${RED_BOLD}"
	cat ./text/wsl-font.txt
	echo -e "Droid Sans Mono Nerd Font Complete Mono Windows Compatible"
	echo -e "${RESET_FORMAT}"
    fi
    user_path=$(find /mnt/c/Users/ -maxdepth 1 -type d -iname $USER_STRING)
    config_path=$user_path/AppData/Roaming/wsltty
    # Backup file
    rsync -rv --no-links $config_path/config "$BACKUP_DIR/wsltty/"
    # Link to dotfile
    # ln -svf "$(pwd)/terminal/wsltty/config" $config_path
    cp -fv "$(pwd)/terminal/wsltty/config" $config_path/
fi

# Setup configuration for Linux terminal
if [[ $(get_os) = 'linux' ]]; then
    # Check if the font is installed
    is_font=$(fc-list | grep DroidSansMono) 
    # If not, dowload it in the right folder
    if [[ -z $is_font ]]; then
        mkdir -p $HOME/.local/share/fonts
        cd $HOME/.local/share/fonts 
	url='https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf'	
	font_name="Droid Sans Mono for Powerline Nerd Font Complete.otf"
        curl -fLo $font_name  $url
	cd -
    fi
    # Check if the font is now installed
    is_font=$(fc-list | grep DroidSansMono) 
    # If the installation didn't work fall back on the font present in the repo
    if [[ -z $is_font ]]; then
        cp "./font/$font_name" $HOME/.local/share/fonts
    fi
    # Configure terminal
fi

if [[ "$?" == 0 ]]; then
    echo 'Terminal configuration installation complete'
fi

