#!/usr/bin/env bash

readonly BACKUP_DIR=~/dotfiles/backup/vim/
readonly BASE_DIR=$(dirname "$0")/..

cd "$(pwd)/$BASE_DIR" || exit 1

source ./scripts/colors

echo -e "${BLUE}Seting up Vim configuration ${RESET_FORMAT}"

# Create the undodir directory if it doesn't exist
if [[ ! -d "$HOME/.vim/undodir/" ]]; then
    mkdir -pv "$HOME/.vim/undodir/"
fi

# Create the ftplugin directry if it doesn't exist
if [[ ! -d "$HOME/.vim/after/ftplugin/" ]]; then
    mkdir -pv "$HOME/.vim/after/ftplugin/"
fi

# Create a ftplugin directory in the backup directory if it doesn't exist
if [[ ! -d "$BACKUP_DIR/ftplugin/" ]]; then
    mkdir -pv "$BACKUP_DIR/ftplugin"
fi

# Backup existing ftplugin files into the backup directory
for f in $HOME/.vim/after/ftplugin/*.vim; do
    rsync -v --no-links --ignore-existing $f "$BACKUP_DIR/ftplugin/"
done

# Link ftplugin files from dotfiles to the .vim directory
shopt -s nullglob
for f in ./vim/ftplugin/*.vim; do
    basename=$(basename "$f")
    ln -svf "$(pwd)/vim/ftplugin/$basename" "$HOME/.vim/after/ftplugin/"
done

if [[ "$?" == 0 ]]; then
    echo -e "${GREEN}Vim setup complete ${RESET_FORMAT}"
fi

