#!/usr/bin/env bash

readonly BACKUP_DIR=~/dotfiles/backup/vim/
readonly BASE_DIR=$(dirname "$0")/..

cd "$(pwd)/$BASE_DIR" || exit 1

source ./scripts/helpers.sh

msg_info 'Seting up Vim configuration'

# Create the undodir directory if it doesn't exist
mkdir -pv "$HOME/.vim/undodir/"

# Create the ftplugin directry if it doesn't exist
mkdir -pv "$HOME/.vim/after/ftplugin/"

# Create a ftplugin directory in the backup directory if it doesn't exist
mkdir -pv "$BACKUP_DIR/ftplugin"

# Link ftplugin files from dotfiles to the .vim directory
shopt -s nullglob # Avoid to grab hardcoded * if directory is empty
for f in ./vim/ftplugin/*.vim; do
    basename=$(basename "$f")
    # Backup existing ftplugin file into the backup directory
    if [[ -f "$HOME/.vim/after/ftplugin/$basename" ]]; then
	backup_file "$HOME/.vim/after/ftplugin/$basename" "$BACKUP_DIR/ftplugin/"
    fi
    make_link "$(pwd)/vim/ftplugin/$basename" "$HOME/.vim/after/ftplugin/"
done

if [[ "$?" == 0 ]]; then
    msg_success 'Vim setup complete'
fi

